services:
  postgres:
    image: ankane/pgvector:latest
    container_name: my_postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=nopass
      - POSTGRES_DB=bookvexedb_j2e
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
