-- CREATE TABLE knowledge
-- (
--     id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     title      VARCHAR(255),
--     content    TEXT,
--     embedding VECTOR(1536),
--     created_at TIMESTAMP WITHOUT TIME ZONE,
--     CONSTRAINT pk_knowledge PRIMARY KEY (id)
-- );

ALTER TABLE notifications
    ADD is_read BOOLEAN;