ALTER TABLE bookings
    DROP FOREIGN KEY FK_BOOKINGS_ON_USERID;

ALTER TABLE bookings
    ADD customer_id BINARY(16) NULL;

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_CUSTOMERID FOREIGN KEY (customer_id) REFERENCES customer (uuid);

ALTER TABLE bookings
    DROP COLUMN user_id;